// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl_SnWlmbw00ha8Ejaa35i9g2dSrV7UO8',
    appId: '1:689143295966:web:d712e442e13564fc76374f',
    messagingSenderId: '689143295966',
    projectId: 'kegiatannvolunteer',
    authDomain: 'kegiatannvolunteer.firebaseapp.com',
    databaseURL: 'https://kegiatannvolunteer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kegiatannvolunteer.firebasestorage.app',
    measurementId: 'G-1VMDW2ZNDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO9XgU1sCQVzuerU-WqCuXflbgqnWbj4A',
    appId: '1:689143295966:android:61bed108790854f176374f',
    messagingSenderId: '689143295966',
    projectId: 'kegiatannvolunteer',
    databaseURL: 'https://kegiatannvolunteer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kegiatannvolunteer.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl_SnWlmbw00ha8Ejaa35i9g2dSrV7UO8',
    appId: '1:689143295966:web:54f0b316555aaed676374f',
    messagingSenderId: '689143295966',
    projectId: 'kegiatannvolunteer',
    authDomain: 'kegiatannvolunteer.firebaseapp.com',
    databaseURL: 'https://kegiatannvolunteer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kegiatannvolunteer.firebasestorage.app',
    measurementId: 'G-CJTJT5BRWL',
  );
}
